### ISSUE TITLE
Question: Java Only

### ISSUE THREAD

**Issue by domfarolino** [maiquynhtruong/Leetcode#1]
Title says it. Do you want this repo to be Java contributions only?

**Comment by maiquynhtruong** [comment]
Oh hey Dom!
For now, yes. I need to be strong in one programming language. I'm polishing my skills on Java now. I want to be proficient in Java data structures (Collections Interfaces, Set, List, Map, Queue interfaces and all the classes implementing them such as HashSet, HashMap, LinkedHashMap, etc), and some classes that are helpful for solving problems (StringBuilder, Integer, StringTokenizer, etc). Some problems might be faster or more efficient if solved in some other languages (Python, Cpp), but for now I don't have time to solve one problem in multiple languages. I will try to do so in the future.

But if you're thinking about contributing in other programming languages, I'd love to merge! Thanks for noticing my repo 👍 😄 Hope to see you around campus 😃 I would love to discuss more about problem solving with you 😄

**Comment by domfarolino** [comment]
Understood. Yeah the Java collections library is very vast! I'll probably be contributing some stuff in C++ if that works (my main proficient language). Regarding your last paragraph, likewise we should meet up. What classes are you taking this semester?

**Comment by maiquynhtruong** [comment]
I'll be happy pull in any of your PRs. I'm excited to meet up with you, too. Since this comment is quite on time for the ACM meeting today, I hope to see you after the meeting and talk about what classes I have this term :)
